export const STATES = {
  JAMMING: "JAMMING",
  RECORDING: "RECORDING",
  PLAYING: "PLAYING",
};

export const EVENTS = {
  TOGGLE_PLAY: "TOGGLE_PLAY",
  TOGGLE_RECORD: "TOGGLE_RECORD",
  SONG_END: "SONG_END",
};

export const ACTIONS = {
  START_PLAYBACK: "START_PLAYBACK",
  STOP_PLAYBACK: "STOP_PLAYBACK",
  ENTER_JAMMING: "ENTER_JAMMING",
  ENTER_RECORDING: "ENTER_RECORDING",
};

export const appMachineConfig = {
  initial: STATES.JAMMING,
  states: {
    [STATES.JAMMING]: {
      entry: [ACTIONS.STOP_PLAYBACK, ACTIONS.ENTER_JAMMING],
      on: {
        [EVENTS.TOGGLE_RECORD]: STATES.RECORDING,
        [EVENTS.TOGGLE_PLAY]: STATES.PLAYING,
      },
    },
    [STATES.RECORDING]: {
      entry: ACTIONS.ENTER_RECORDING,
      on: {
        [EVENTS.TOGGLE_RECORD]: STATES.JAMMING,
        [EVENTS.TOGGLE_PLAY]: STATES.PLAYING,
      },
    },
    [STATES.PLAYING]: {
      entry: ACTIONS.START_PLAYBACK,
      on: {
        [EVENTS.TOGGLE_PLAY]: STATES.JAMMING,
        [EVENTS.SONG_END]: STATES.JAMMING,
      },
    },
  },
};
